Added DevOps Automation Functions
ProjetaAi/projetaai-azure pull request #3
Opened 2023-04-20 13:55 UTC by jordi-advisia

2023-04-24 16:59 UTC, gustavo-advisia requested changes
Na função parameters_ci_create, deixa um exemplo de como deve ficar o yml final de configuração

2023-04-24 16:59 UTC, gustavo-advisia commented on projetaai_azure/cli/devops.py
> +    variables = click.prompt('Dict with environment variables names and values')
Quais variáveis podem ser adicionadas? As outras opções estão bem claras!

2023-04-24 16:59 UTC, gustavo-advisia commented on projetaai_azure/cli/devops.py
> +    """Creates conf/base/parameters_ci.yml, used in commands to automate Azure Dev Ops Management.
Pode deixar aqui na docstring mesmo, um exemplo de como deve ser o arquivo final de configuração, para alguem que quiser ou precisar modificar as funções no final conseguirem ter uma boa base

2023-04-24 16:59 UTC, gustavo-advisia commented on projetaai_azure/cli/devops.py
> +from kedro_projetaai import __version__ as version
Puxar version da projetaai_azure

2023-04-25 20:27 UTC, gustavo-advisia approved these changes

2023-08-14 18:59 UTC, Juanmlops commented
feature não esta sendo utilizada

2023-08-14 18:59 UTC, closed without merging